kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mysql-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: ibmc-block-gold 
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
