# Default values for ibm-ucd chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cp.icr.io/ibm-ucds
  tag: "7.1.0.3.1069281"
  pullPolicy: Always
  secret: ""

service:
  type: ClusterIP

database:
  type: ""
  name: ""
  hostname: ""
  username: ""
  port: ""
  jdbcConnUrl: ""

secureConnections:
  required: true

secret:
  name: ""

ucdLicense:
  serverUrl: ""
# Change license to true to indicate have read and agree to license agreements : http://ibm.biz/ucd-license
  accept: false

persistence:
  enabled: true
  useDynamicProvisioning: false
  fsGroup: 1001

extLibVolume:
  name: "ext-lib"
  existingClaimName: ""
  configMapName: ""
  storageClassName: ""
  size: ""
  accessMode: "ReadWriteOnce"

appDataVolume:
  name: "appdata"
  existingClaimName: ""
  storageClassName: ""
  size: ""
  accessMode: "ReadWriteOnce"

ingress:
  host: ""
  dfehost: ""
  wsshost: ""
  jmshost: ""

resources:
  constraints: 
    enabled: true
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 200m
    memory: 600Mi

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 300
  failureThreshold: 3

