# Default values for ibm-ucd chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: cp.icr.io/ibm-ucds
  tag: "7.1.0.3.1069281"
  pullPolicy: Always
  secret: "entitledregistry-secret"

service:
  type: NodePort

database:
  type: "mysql"
  name: "ibm_ucd"
  hostname: "mysql"
  username: "ibm_ucd"
  port: "3306"
  jdbcConnUrl: "jdbc:mysql://mysql:3306/ibm_ucd"

secureConnections:
  required: true

secret:
  name: "ucd-secrets"

ucdLicense:
  serverUrl: ""
# Change license to true to indicate have read and agree to license agreements : http://ibm.biz/ucd-license
  accept: true

persistence:
  enabled: true
  useDynamicProvisioning: false
  fsGroup: 1001

extLibVolume:
  name: "ext-lib"
  existingClaimName: "ext-lib-pvc"
  configMapName: "user-script"
  storageClassName: "ibmc-vpc-block-10iops-tier"
  size: "10Gi"
  accessMode: "ReadWriteOnce"

appDataVolume:
  name: "appdata"
  existingClaimName: "appdata-pvc"
  storageClassName: "ibmc-vpc-block-10iops-tier"
  size: "20Gi"
  accessMode: "ReadWriteOnce"

ingress:
  host: ""
  dfehost: ""
  wsshost: ""
  jmshost: ""

resources:
  constraints: 
    enabled: true
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 200m
    memory: 600Mi

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
  failureThreshold: 10

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 300
  failureThreshold: 3

